import type { Metadata, Viewport } from "next";
import "./globals.css";
import connectDB from "@/db/connection";
import { NotificationProvider } from "@/lib/components/popups/components/notification/notification-context";

//Initialize MongoDB Connection
await connectDB();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <NotificationProvider>{children}</NotificationProvider>
      </body>
    </html>
  );
}
